version: '3.0'

services:
  redis:
    image: redis
    command: [sh, -c, "rm -rf /data/dump.rdb && redis-server"]
    ports:
      - 6379:6379
    volumes:
      - .:/data:cached

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:cached

volumes:
  db_data:
